### ISSUE TITLE
Hacer pin de datos de simulaciones de tiempos

### ISSUE THREAD

**Issue by felipegonzalez** [cotecora-team-2/estratificacion-simulacion#3]
1. Generar los datos de simulacion según el script estratificacion-simulacion/R/generar-simulaciones.R
2.  Hacer un script cargar-datos.R en estratificacion-simulacion/ (usando un pin) que baje los datos a estratificacion-simulacion/datos, de manera que esta línea funcione después de correr cargar-datos.R:

`sims_tiempos <- read_rds(file = "../datos/simulaciones_completo.rds")`

**Comment by ixime** [comment]
listo, el pull request es #4
